FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu20.04


ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    git \
    curl \
    wget \
    ca-certificates \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get update && apt-get install -y \
    python3.10 \
    python3.10-dev \
    python3.10-distutils \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libgl1 \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 \
    && rm -rf /var/lib/apt/lists/*


RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 \
    && update-alternatives --set python /usr/bin/python3.10

RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir\
    flask \
    flask_socketio \
    flask_wtf \
    eventlet \
    numpy \
    celery \
    opencv-python \
    redis \
    pandas \
    tqdm \
    PyYaml \
    matplotlib \
    seaborn \
    scipy \
    ultralytics \
    gunicorn

RUN pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121

WORKDIR /app

COPY . /app

RUN python --version && pip --version

CMD ["/bin/bash"]