import os
from cortex.app_configurations import BaseConfigurations


CONFIG = {
  "id": "signboard_detection",
  "task_name": "signboard_detection",
  "description": "Detect various types of road signboards in images.",
  "dnnarch": "yolov7",
  "weights_path": os.path.join(BaseConfigurations.WEIGHTS_DIR, 'yolov7_signboard.pt'),
  "input_size": [640, 640],
  "classes": [
    "auto_rickshaw_stand",
    "accident_zone",
    "bus_stop",
    "camera_1",
    "camera_2",
    "car_&_taxi_parking",
    "cattle_area",
    "caution",
    "compulsory_cycle_track",
    "compulsory_keep_left",
    "compulsory_keep_right",
    "compulsory_turn_right",
    "cross_road",
    "curve_road_ahead",
    "danger_zone",
    "dangerous_dip",
    "diversion_ahead",
    "divide_road_ahead",
    "divide_road_end",
    "divide_two_side",
    "eating_place_ahead",
    "falling_rocks",
    "foot_over_bridge",
    "gap_in_median",
    "give_way",
    "go_slow",
    "guarded_ahead",
    "height_limit",
    "horn_compulsory",
    "horn_prohibited",
    "hospital_ahead",
    "htv_prohibited",
    "junction_ahead",
    "left_curve_ahead",
    "left_hair_pin_bend",
    "left_hand_curve",
    "left_reverse_bend",
    "left_road_merging_ahead",
    "left_turn_prohibited",
    "men_at_work",
    "narrow_bridge_ahead",
    "narrow_road_ahead",
    "no_entry",
    "no_parking",
    "no_parking_rb",
    "no_stopping_and_no_parking",
    "one_way",
    "overtaking_prohibited",
    "parking_ahead",
    "pedestrian_crossing",
    "pedestrian_walking",
    "petrol_pump",
    "petrol_pump_ahead",
    "public_telephone_ahead",
    "right_curve_ahead",
    "right_hair_pin_bend",
    "right_hand_curve",
    "right_reverse_bend",
    "right_road_merging_ahead",
    "right_turn_prohibited",
    "road_closed",
    "road_widen_ahead",
    "round_about_ahead",
    "school_ahead_1",
    "school_ahead_2",
    "side_road_left",
    "side_road_right",
    "speed_breaker",
    "speed_breaker_c3",
    "speed_breaker_c4",
    "speed_limit",
    "speed_limit_2",
    "staggered_junction",
    "steep_ascend",
    "stop",
    "t_junction_ahead",
    "toilet_ahead",
    "towing_zone",
    "traffic_light_1",
    "traffic_light_2",
    "traffic_light_3",
    "traffic_light_board",
    "two_way_road",
    "two_wheeler_parking",
    "u_turn_allow",
    "u_turn_prohibited",
    "y_intersection",
    "y_intersection_left",
    "y_intersection_right",
    "zebra_crossing",
    "zigzag_road",
    "TBD"
  ],
  "confidence_threshold": 0.5,
  "nms_threshold": 0.45
}


